theme: jekyll-theme-minimal
title: RAGE 2 Modding Toolkit
description: Portable GUI toolkit for extracting, editing and repacking RAGE 2 .arc archives. 91.41% gameplay coverage.
show_downloads: true

url: https://shtnt.github.io
baseurl: /Rage-2-Modding-Toolkit
lang: en

author:
  name: Kry0genik
  url: https://github.com/shTNT

github:
  repository_url: https://github.com/shTNT/Rage-2-Modding-Toolkit
  is_project_page: true
  repository_name: Rage-2-Modding-Toolkit
  owner_name: shTNT

keywords: RAGE 2, modding, toolkit, arc, avtx, ddsc, murmerhash, apex engine, avalanche, repack, extract, dds, textures