<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RAGE2Toolkit</AssemblyName>
    <RootNamespace>Rage2Toolkit</RootNamespace>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>false</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <Version>2.0.3</Version>
    <AssemblyVersion>2.0.3.0</AssemblyVersion>
    <FileVersion>2.0.3</FileVersion>
    <InformationalVersion>2.0.3</InformationalVersion>
        <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>fragoneta.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
    <NoWarn>CS0162;CS0414;CS0219;CS0168</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Rage2Toolkit.cs" />
    <Compile Include="ExtractorOpt.cs" />
    <Compile Include="SingleExtractForm.cs" />
    <Compile Include="Repack.cs" />
    <Compile Include="RepackerCore.cs" />
    <Compile Include="Wizards.cs" />
    <Compile Include="Updater.cs" />
    <Compile Include="CrashHandler.cs" />
    <Compile Include="Dialogs.cs" />
    <Compile Include="AssetConverters.cs" />
    <Compile Include="AssetValidators.cs" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
</Project>



