<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>RAGE2Toolkit</AssemblyName>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishSingleFile>false</PublishSingleFile>
    <Version>1.3.0</Version>
    <ApplicationIcon>fragoneta.ico</ApplicationIcon>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <Optimize>true</Optimize>
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
    <TieredPGO>true</TieredPGO>
    <NoWarn>CS0162;CS0414;CS0219;CS0168</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Rage2Toolkit.cs" />
    <Compile Include="Repack.cs" />
    <Compile Include="Wizards.cs" />
  </ItemGroup>
</Project>